/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.UsuariosBjf;
import consultas.JDLgConsultaUsuario;
import dao.UsuariosDAOBjf;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import pesquisa.JDlgUsuariosPesquisaBjf;
import tools.Util;

/**
 *
 * @author 
 */
public class JDlgUsuariosBjf extends javax.swing.JDialog {
    private JDlgUsuariosPesquisaBjf jDlgUsuariosPesquisaBjf;
    private boolean incluir;
    MaskFormatter maskcpf;
    MaskFormatter maskdatanascimento;
    Util util;
    JDLgConsultaUsuario jDlgConsultaUsuario;
    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgUsuariosBjf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Usuarios");
        setLocationRelativeTo(null);  
        
       try {
            maskcpf = new MaskFormatter("###.###.###-##");
            maskdatanascimento = new MaskFormatter("##/##/####");
            
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCpfBjf.setFormatterFactory(new DefaultFormatterFactory(maskcpf));
        jFmtDataNascimentoBjf.setFormatterFactory(new DefaultFormatterFactory(maskdatanascimento));
        
        Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        jBtnIncluir.setEnabled(true);
        Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
    }
    
     public UsuariosBjf viewBean() {
        UsuariosBjf usuariosBjf = new UsuariosBjf();
        int id = Util.strInt(jTxtCodigoBjf.getText());
        Date dataNascimento = Util.strDate(jFmtDataNascimentoBjf.getText());
        usuariosBjf.setDataNascBjf(dataNascimento);
        usuariosBjf.setIdusuariosBjf(id);
        usuariosBjf.setNomeBjf(jTxtNomeBjf.getText());
        usuariosBjf.setEmailBjf(jTxtEmailBjf.getText());
        usuariosBjf.setSenhaBjf(jPwfSenhaBjf.getText());
        usuariosBjf.setCpfBjf(jFmtCpfBjf.getText());
        if(jChbAtivo.isSelected()==true){
        usuariosBjf.setAtivoBjf("S");
        } else {
        usuariosBjf.setAtivoBjf("N");
        }
        if ((jCboSexo.getSelectedIndex() == 1)) {
            usuariosBjf.setSexoBjf("H");
        }else {
            usuariosBjf.setSexoBjf("M"); 
        }
        return usuariosBjf;

    }

    public void beanView(UsuariosBjf usuariosBjf) {

        String intStr = Util.intStr(usuariosBjf.getIdusuariosBjf());
        String dataNascimento = Util.dateStr(usuariosBjf.getDataNascBjf());

        jTxtCodigoBjf.setText(intStr);
        jFmtDataNascimentoBjf.setText(dataNascimento);
        jTxtNomeBjf.setText(usuariosBjf.getNomeBjf());
        jTxtEmailBjf.setText(usuariosBjf.getEmailBjf());
        jPwfSenhaBjf.setText(usuariosBjf.getSenhaBjf());
        jFmtCpfBjf.setText(usuariosBjf.getCpfBjf());
        String sexo = usuariosBjf.getSexoBjf();
        if(sexo.equals("Homem")){
            jCboSexo.setSelectedIndex(0);
        }else {
            jCboSexo.setSelectedIndex(1);
        }
        if(usuariosBjf.getAtivoBjf().equals("S") == true){
            jChbAtivo.setSelected(true);
        } else {
            jChbAtivo.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jFmtCpfBjf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jBtnAlterar = new javax.swing.JButton();
        jTxtEmailBjf = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jTxtNomeBjf = new javax.swing.JTextField();
        jChbAtivo = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jCboSexo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtCodigoBjf = new javax.swing.JTextField();
        jPwfSenhaBjf = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jFmtDataNascimentoBjf = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jBtnCancelar = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnConfirmar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setForeground(new java.awt.Color(255, 0, 204));
        jLabel5.setText("DATA DE NASCIMENTO:");

        jFmtCpfBjf.setForeground(new java.awt.Color(255, 0, 153));
        jFmtCpfBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpfBjfActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setText("EMAIL:");

        jBtnAlterar.setBackground(new java.awt.Color(255, 0, 204));
        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jTxtEmailBjf.setForeground(new java.awt.Color(255, 0, 204));
        jTxtEmailBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmailBjfActionPerformed(evt);
            }
        });

        jBtnIncluir.setBackground(new java.awt.Color(255, 0, 204));
        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jTxtNomeBjf.setForeground(new java.awt.Color(255, 0, 153));
        jTxtNomeBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeBjfActionPerformed(evt);
            }
        });

        jChbAtivo.setForeground(new java.awt.Color(255, 0, 204));
        jChbAtivo.setText("Ativo");

        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("NOME:");

        jCboSexo.setForeground(new java.awt.Color(255, 0, 204));
        jCboSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "H", "M" }));
        jCboSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboSexoActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Código:");

        jLabel7.setForeground(new java.awt.Color(255, 0, 204));
        jLabel7.setText("SEXO:");

        jTxtCodigoBjf.setForeground(new java.awt.Color(255, 0, 153));
        jTxtCodigoBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodigoBjfActionPerformed(evt);
            }
        });

        jPwfSenhaBjf.setForeground(new java.awt.Color(255, 0, 153));

        jLabel6.setForeground(new java.awt.Color(255, 0, 153));
        jLabel6.setText("SENHA:");

        jFmtDataNascimentoBjf.setForeground(new java.awt.Color(255, 0, 204));
        jFmtDataNascimentoBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataNascimentoBjfActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 0, 204));
        jLabel9.setText("Você está ativo?");

        jBtnCancelar.setBackground(new java.awt.Color(255, 0, 204));
        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jBtnPesquisar.setBackground(new java.awt.Color(255, 0, 204));
        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnConfirmar.setBackground(new java.awt.Color(255, 0, 204));
        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("CPF:");

        jBtnExcluir.setBackground(new java.awt.Color(255, 0, 204));
        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/checkered_flag.png"))); // NOI18N
        jButton1.setText("CONSULTAR MEU USUARIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 153), new java.awt.Color(255, 0, 51), new java.awt.Color(255, 0, 102)));

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 153));
        jLabel8.setText("Cadastro de Usuários");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPwfSenhaBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtCpfBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtCodigoBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jFmtDataNascimentoBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTxtEmailBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jChbAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(44, 44, 44))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTxtCodigoBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jFmtDataNascimentoBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtEmailBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtCpfBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPwfSenhaBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbAtivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCancelar)
                        .addComponent(jBtnPesquisar)
                        .addComponent(jBtnAlterar)
                        .addComponent(jBtnIncluir))
                    .addComponent(jBtnExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmtCpfBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpfBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpfBjfActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        incluir = false;
        
        Util.habilitar(false, jBtnIncluir, jBtnExcluir, jBtnPesquisar, jBtnAlterar);
        Util.habilitar(true, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jTxtEmailBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmailBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmailBjfActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        incluir = true;
        
        Util.habilitar(false, jBtnIncluir, jBtnExcluir, jBtnPesquisar, jBtnAlterar);
        Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
        Util.habilitar(true, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jTxtNomeBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeBjfActionPerformed

    private void jCboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboSexoActionPerformed

    private void jTxtCodigoBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodigoBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodigoBjfActionPerformed

    private void jFmtDataNascimentoBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataNascimentoBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataNascimentoBjfActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
         Util.mensagem("Operação cancelada!");
         
         Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
         Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        jDlgUsuariosPesquisaBjf = new JDlgUsuariosPesquisaBjf(null, true);
        jDlgUsuariosPesquisaBjf.setTitle("Pesquisar");
        jDlgUsuariosPesquisaBjf.setTelaAnterior(this);
        jDlgUsuariosPesquisaBjf.setVisible(true);
        
        Util.habilitar(true, jBtnIncluir, jBtnAlterar , jBtnExcluir);
        Util.habilitar(false, jBtnCancelar, jBtnConfirmar); 
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
    UsuariosBjf usuariosBjf = viewBean();
    UsuariosDAOBjf usuariosDAOBjf = new UsuariosDAOBjf();
    
    if (incluir == true) {
        
        usuariosDAOBjf.insert(usuariosBjf);
        Util.mensagem("Registro incluido com sucesso.");
        
    } else {
        
        usuariosDAOBjf.update(usuariosBjf);
        Util.mensagem("Registro alterado com sucesso.");
        
    }
    Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
    Util.habilitar(true, jBtnIncluir,jBtnPesquisar);
    Util.habilitar(false, jBtnAlterar,jBtnCancelar,jBtnConfirmar,jBtnExcluir,jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
    if (Util.perguntar("Deseja excluir o registro?") == true) {
        
        UsuariosBjf usuariosBjfu = viewBean();
        UsuariosDAOBjf usuariosDAOBjf = new UsuariosDAOBjf();
        usuariosDAOBjf.delete(usuariosBjfu);
        
        Util.mensagem("Registro Excluido.");
        
    }else{
        
        Util.mensagem("Exclusão Cancelada.");
        
       }
    Util.limparCampos(jTxtCodigoBjf,jTxtNomeBjf,jFmtCpfBjf,jPwfSenhaBjf,jFmtDataNascimentoBjf,jTxtEmailBjf,jCboSexo,jChbAtivo);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDlgConsultaUsuario = new JDLgConsultaUsuario(null, true);

        jDlgConsultaUsuario.setTitle("Consultar");
        jDlgConsultaUsuario.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuariosBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuariosBjf dialog = new JDlgUsuariosBjf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCboSexo;
    private javax.swing.JCheckBox jChbAtivo;
    private javax.swing.JFormattedTextField jFmtCpfBjf;
    private javax.swing.JFormattedTextField jFmtDataNascimentoBjf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPwfSenhaBjf;
    private javax.swing.JTextField jTxtCodigoBjf;
    private javax.swing.JTextField jTxtEmailBjf;
    private javax.swing.JTextField jTxtNomeBjf;
    // End of variables declaration//GEN-END:variables

}