/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.ClienteBjf;
import dao.ClientesDAO;
import java.text.ParseException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import pesquisa.JDlgClientePesquisaBjf;
import tools.Util;

/**
 *
 * @author u03402615100
 */
public class JDlgClientesBjf extends javax.swing.JDialog {

    private boolean incluir;
    private JDlgClientePesquisaBjf jDlgClientePesquisaBjf;
    MaskFormatter maskcep;
    MaskFormatter maskcpf;
    MaskFormatter maskdataregistro;
    MaskFormatter maskrg;
    MaskFormatter maskdatanascimento;
    MaskFormatter masktelefone;

    /**
     * Creates new form JDlgClientes
     */
    public JDlgClientesBjf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Clientes");
        setLocationRelativeTo(null);
        try {
            maskcep = new MaskFormatter("#####-###");
            maskcpf = new MaskFormatter("###.###.###-##");
            maskdataregistro = new MaskFormatter("##/##/####");
            maskrg = new MaskFormatter("#.###.###");
            maskdatanascimento = new MaskFormatter("##/##/####");
            masktelefone = new MaskFormatter("(##)#####-####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgClientesBjf.class.getName()).log(Level.SEVERE, null, ex);
        }
        jFmtCEP.setFormatterFactory(new DefaultFormatterFactory(maskcep));
        jFmtCPFBjf.setFormatterFactory(new DefaultFormatterFactory(maskcpf));
        jFmtDataNasc.setFormatterFactory(new DefaultFormatterFactory(maskdatanascimento));
        jFmtDataRegistro.setFormatterFactory(new DefaultFormatterFactory(maskdataregistro));
        jFmtRGBjf.setFormatterFactory(new DefaultFormatterFactory(maskrg));
        jFmtTelefoneBjf.setFormatterFactory(new DefaultFormatterFactory(masktelefone));

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         *
         * @return
         */
        Util.habilitar(false, jTxtPaisBjf, jFmtCodigo, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.limparCampos(jTxtPaisBjf, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        jBtnIncluir.setEnabled(true);
    }

    public ClienteBjf viewBean() {
        ClienteBjf cliente = new ClienteBjf();
        int id = Util.strInt(jFmtCodigo.getText());

        Date dataNascimento = Util.strDate(jFmtDataNasc.getText());
        Date dataRegistro = Util.strDate(jFmtDataRegistro.getText());
        cliente.setIdclienteBjf(id);
        cliente.setNomeBjf(jTxtNomeBjf.getText());
        cliente.setDataNascBjf(dataNascimento);
        cliente.setDataRegistroBjf(dataRegistro);
        cliente.setProfissaoBjf(jTxtProfissao.getText());
        cliente.setCpfBjf(jFmtCPFBjf.getText());
        cliente.setEmailBjf(jTxtEmail.getText());
        cliente.setRgBjf(jFmtRGBjf.getText());
        cliente.setEnderecoBjf(jTxtEndereço.getText());
        cliente.setCidadeBjf(jTxtCidade.getText());
        cliente.setTelefoneBjf(jFmtTelefoneBjf.getText());
        cliente.setPaisBjf(jTxtPaisBjf.getText());

        cliente.setEstadoBjf(jTxtEstado.getText());
        cliente.setCepBjf(jFmtCEP.getText());
        cliente.setRgBjf(jFmtRGBjf.getText());

        if ((jCboEstado.getSelectedIndex() == 1)) {
            cliente.setEstadoCivilBjf("Casado");
        } else if ((jCboEstado.getSelectedIndex() == 2)) {
            cliente.setEstadoCivilBjf("Solteiro");
        } else if ((jCboEstado.getSelectedIndex() == 3)) {
            cliente.setEstadoCivilBjf("Namorando");
        } else {
            cliente.setEstadoCivilBjf("Abandonado");
        }

        return cliente;
    }

    public void beanView(ClienteBjf cliente) {

        String intStr = Util.intStr(cliente.getIdclienteBjf());
        jFmtCodigo.setText(intStr);

        jFmtDataNasc.setText(Util.dateStr(cliente.getDataNascBjf()));
        jFmtDataRegistro.setText(Util.dateStr(cliente.getDataRegistroBjf()));
        jTxtNomeBjf.setText(cliente.getNomeBjf());
        jFmtCEP.setText(cliente.getCepBjf());
        jTxtProfissao.setText(cliente.getProfissaoBjf());
        jTxtEmail.setText(cliente.getEmailBjf());
        jFmtCPFBjf.setText(cliente.getCpfBjf());
        jTxtEndereço.setText(cliente.getEnderecoBjf());
        jTxtCidade.setText(cliente.getCidadeBjf());
        jFmtTelefoneBjf.setText(cliente.getTelefoneBjf());
        jTxtEstado.setText(cliente.getEstadoBjf());
        jFmtRGBjf.setText(cliente.getRgBjf());
        jTxtPaisBjf.setText(cliente.getPaisBjf());

        String estadoCivil = cliente.getEstadoCivilBjf();
        if (estadoCivil.equals("Casado")) {
            jCboEstado.setSelectedIndex(0);
        } else if (estadoCivil.equals("abandonado")) {
            jCboEstado.setSelectedIndex(1);
        } else if (estadoCivil.equals("procurando um amor")) {
            jCboEstado.setSelectedIndex(2);
        } else {
            jCboEstado.setSelectedIndex(3);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTxtCidade = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jTxtProfissao = new javax.swing.JFormattedTextField();
        jFmtDataNasc = new javax.swing.JFormattedTextField();
        jCboEstado = new javax.swing.JComboBox<>();
        jLabelGenero = new javax.swing.JLabel();
        jTxtEndereço = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtEstado = new javax.swing.JTextField();
        jBtnIncluir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabelNaturalidade = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jFmtCEP = new javax.swing.JFormattedTextField();
        jFmtCPFBjf = new javax.swing.JFormattedTextField();
        jFmtTelefoneBjf = new javax.swing.JFormattedTextField();
        jTxtNomeBjf = new javax.swing.JTextField();
        jBtnCancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jBtnPesquisar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jBtnConfirmar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jFmtCodigo = new javax.swing.JFormattedTextField();
        jFmtRGBjf = new javax.swing.JFormattedTextField();
        jFmtDataRegistro = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtPaisBjf = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 51, 153));
        jLabel1.setFont(new java.awt.Font("Georgia", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Cadastro de Clientes");

        jLabelCPF.setText("CPF");

        jTxtProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtProfissaoActionPerformed(evt);
            }
        });

        jCboEstado.setForeground(new java.awt.Color(255, 0, 153));
        jCboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASADO", "SOLTEIRO", "NAMORANDO", "ABANDONADO", " " }));
        jCboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboEstadoActionPerformed(evt);
            }
        });

        jLabelGenero.setForeground(new java.awt.Color(102, 0, 102));
        jLabelGenero.setText("Estado Civil");

        jLabel5.setText("Telefone");

        jLabel4.setText("Data de Nascimento");

        jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jLabel9.setText("Profissão");

        jLabelNaturalidade.setText("Endereço");

        jLabelEmail.setText("Email");

        jLabelNome.setText("Nome");

        jFmtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCEPActionPerformed(evt);
            }
        });

        jFmtCPFBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCPFBjfActionPerformed(evt);
            }
        });

        jTxtNomeBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeBjfActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar_1.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel14.setText("CEP");

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar_1.png"))); // NOI18N
        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jLabel13.setText("Estado");

        jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar.setText("Confirmar");
        jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmarActionPerformed(evt);
            }
        });

        jLabel12.setText("Cidade ");

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_1.png"))); // NOI18N
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jLabel10.setText("Data Registro");

        jLabel2.setText("RG");

        jLabel3.setText("Código");

        jFmtRGBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtRGBjfActionPerformed(evt);
            }
        });

        jLabel6.setText("Pais");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jFmtDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNaturalidade)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTxtEndereço)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(118, 118, 118)))
                                .addGap(15, 15, 15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(107, 107, 107)
                                .addComponent(jLabel12))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jFmtRGBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelEmail)
                                            .addGap(271, 271, 271)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jFmtTelefoneBjf)))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFmtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelNome)
                                                .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jFmtCPFBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelCPF))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelGenero)
                                                .addComponent(jCboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(75, 75, 75)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtPaisBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnIncluir)
                        .addGap(17, 17, 17)
                        .addComponent(jBtnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnConfirmar)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnCancelar)
                    .addGap(18, 18, 18)
                    .addComponent(jBtnPesquisar)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelCPF)
                                            .addComponent(jLabelGenero))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jFmtCPFBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(1, 1, 1)
                                .addComponent(jFmtRGBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelEmail)
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtTelefoneBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(jLabelNaturalidade)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtDataRegistro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtPaisBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnExcluir)
                            .addComponent(jBtnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnIncluir)
                            .addComponent(jBtnAlterar))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(257, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnPesquisar)
                        .addComponent(jBtnCancelar))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboEstadoActionPerformed

    private void jFmtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCEPActionPerformed

    private void jFmtCPFBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCPFBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCPFBjfActionPerformed

    private void jTxtNomeBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeBjfActionPerformed

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        jDlgClientePesquisaBjf = new JDlgClientePesquisaBjf(null, true);
        jDlgClientePesquisaBjf.setTitle("Pesquisar");
        jDlgClientePesquisaBjf.setTelaAnterior(this);
        jDlgClientePesquisaBjf.setVisible(true);

        Util.habilitar(true, jBtnIncluir, jBtnAlterar, jBtnExcluir);
        Util.habilitar(false, jBtnCancelar, jBtnConfirmar);
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.mensagem("Operação Cancelada!");
        Util.limparCampos(jTxtPaisBjf, jFmtCodigo, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
        Util.habilitar(false, jTxtPaisBjf, jBtnCancelar, jBtnConfirmar, jBtnAlterar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        incluir = false;

        Util.habilitar(true, jTxtPaisBjf, jBtnConfirmar, jBtnCancelar, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar, jFmtCodigo);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmarActionPerformed
        ClienteBjf clienteBjf = viewBean();
        ClientesDAO clientesDAOBjf = new ClientesDAO();

        if (incluir == true) {

            clientesDAOBjf.insert(clienteBjf);
            Util.mensagem("Registro incluido com sucesso.");

        } else {

            clientesDAOBjf.update(clienteBjf);
            Util.mensagem("Registro alterado com sucesso.");

        }

        Util.habilitar(false, jTxtPaisBjf, jBtnConfirmar, jBtnCancelar, jFmtCodigo, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.limparCampos(jTxtPaisBjf, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.habilitar(true, jBtnIncluir, jBtnPesquisar);
    }//GEN-LAST:event_jBtnConfirmarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        incluir = true;

        Util.habilitar(true, jTxtPaisBjf, jBtnConfirmar, jBtnCancelar, jFmtCodigo, jBtnAlterar, jBtnCancelar, jBtnConfirmar, jBtnExcluir, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.limparCampos(jTxtPaisBjf, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
        Util.habilitar(false, jBtnIncluir, jBtnAlterar, jBtnExcluir, jBtnPesquisar);
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        if (Util.perguntar("Deseja excluir o registro?") == true) {

            ClienteBjf clienteBjf = viewBean();
            ClientesDAO clientesDAO = new ClientesDAO();
            clientesDAO.delete(clienteBjf);
            Util.mensagem("Registro Excluido.");

        } else {

            Util.mensagem("Exclusão Cancelada.");

        }

        Util.limparCampos(jTxtPaisBjf, jFmtCodigo, jTxtNomeBjf, jTxtNomeBjf, jFmtDataNasc, jTxtEmail, jCboEstado, jFmtTelefoneBjf, jFmtRGBjf, jFmtCPFBjf, jTxtProfissao, jTxtEndereço, jTxtEstado, jTxtCidade, jFmtCEP, jFmtDataRegistro);
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jFmtRGBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtRGBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtRGBjfActionPerformed

    private void jTxtProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtProfissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtProfissaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClientesBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClientesBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClientesBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClientesBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClientesBjf dialog = new JDlgClientesBjf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnConfirmar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboEstado;
    private javax.swing.JFormattedTextField jFmtCEP;
    private javax.swing.JFormattedTextField jFmtCPFBjf;
    private javax.swing.JFormattedTextField jFmtCodigo;
    private javax.swing.JFormattedTextField jFmtDataNasc;
    private javax.swing.JFormattedTextField jFmtDataRegistro;
    private javax.swing.JFormattedTextField jFmtRGBjf;
    private javax.swing.JFormattedTextField jFmtTelefoneBjf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNaturalidade;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtEndereço;
    private javax.swing.JTextField jTxtEstado;
    private javax.swing.JTextField jTxtNomeBjf;
    private javax.swing.JTextField jTxtPaisBjf;
    private javax.swing.JFormattedTextField jTxtProfissao;
    // End of variables declaration//GEN-END:variables

}
