/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CONTROLEBJF.VendasProdutoControleBjf;
import bean.ProdutoBjf;
import bean.ProdutoVendasBjf;
import dao.ProdutoDAO;
import java.util.ArrayList;
import java.util.List;
import tools.Util;

/**
 *
 * @author duals
 */
public class JDlgVendasProduto extends javax.swing.JDialog {
    
    ProdutoBjf produtobjf;
    VendasProdutoControleBjf vendasprodcontrole;
    JDlgVendasBjf jDlgVendas;

    /**
     * Creates new form JDlgVendasProduto
     */
    public JDlgVendasProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        ProdutoDAO produtoDAO = new ProdutoDAO();
        
        List listaProduto = produtoDAO.listAll();
        
        for (int i = 0; i < listaProduto.size(); i++) {
            jCboProduto.addItem((ProdutoBjf) listaProduto.get(i));
        }
        
        jFmtTotalBjf.setEnabled(false);
    }
    
    public ProdutoVendasBjf viewBean() {
        ProdutoVendasBjf produtovendasBjf = new ProdutoVendasBjf();
        int quantidade = Util.strInt(jFmtQuantiBjf.getText());
        double valorU = Util.strDouble(jFmtValorUniBjf.getText());
        produtovendasBjf.setProdutoBjf((ProdutoBjf) jCboProduto.getSelectedItem());
        produtovendasBjf.setValorUnitarioBjf(valorU);
        produtovendasBjf.setQuantidadeBjf(quantidade);
        
        return produtovendasBjf;
    }
    
    public void beanView(ProdutoVendasBjf produtoVendasBjf) {
        String intStr = Util.intStr(produtoVendasBjf.getQuantidadeBjf());
        String total = Util.doubleStr(produtoVendasBjf.getValorUnitarioBjf());
        jCboProduto.setSelectedItem(produtoVendasBjf.getProdutoBjf());
        jFmtQuantiBjf.setText(Util.intStr(produtoVendasBjf.getQuantidadeBjf()));
        jFmtValorUniBjf.setText(Util.doubleStr(produtoVendasBjf.getValorUnitarioBjf()));
    }
    
    public void setTelaAnterior(JDlgVendasBjf jDlgVendasBjf) {
        this.jDlgVendas = jDlgVendasBjf;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jCboProduto = new javax.swing.JComboBox<>();
        jFmtQuantiBjf = new javax.swing.JFormattedTextField();
        jFmtValorUniBjf = new javax.swing.JFormattedTextField();
        jFmtTotalBjf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnOkBjf = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Tela de Vendas");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCboProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboProdutoItemStateChanged(evt);
            }
        });

        jFmtQuantiBjf.setText("1");
        jFmtQuantiBjf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFmtQuantiBjfFocusLost(evt);
            }
        });
        jFmtQuantiBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtQuantiBjfActionPerformed(evt);
            }
        });
        jFmtQuantiBjf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFmtQuantiBjfKeyReleased(evt);
            }
        });

        jFmtValorUniBjf.setText("1.0");
        jFmtValorUniBjf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFmtValorUniBjfKeyReleased(evt);
            }
        });

        jFmtTotalBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtTotalBjfActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("QUANTIDADE");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("VALOR UNITARIO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("TOTAL");

        jBtnOkBjf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnOkBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkBjfActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setText("VENDAS PRODUTO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jFmtQuantiBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(jFmtValorUniBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                            .addComponent(jFmtTotalBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(138, 138, 138)
                            .addComponent(jBtnOkBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFmtValorUniBjf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jFmtTotalBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtQuantiBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnOkBjf)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFmtTotalBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtTotalBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtTotalBjfActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        Util.mensagem("Operação Cancelada!");
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jBtnOkBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkBjfActionPerformed
        ProdutoVendasBjf produtovendasbjf = new ProdutoVendasBjf();
        VendasProdutoControleBjf vendasprodutocontrole = new VendasProdutoControleBjf();
        produtovendasbjf.setProdutoBjf((ProdutoBjf) jCboProduto.getSelectedItem());
        produtovendasbjf.setQuantidadeBjf(Util.strInt(jFmtQuantiBjf.getText()));
        produtovendasbjf.setValorUnitarioBjf(Util.strDouble(jFmtValorUniBjf.getText()));
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
            jDlgVendas.vendaprodutoControleBjf.addBean(produtovendasbjf);
        } else {
            jDlgVendas.vendaprodutoControleBjf.updateBean(jDlgVendas.getSelectedRowProd(), produtovendasbjf);
        }
        Util.limparCampos(jFmtQuantiBjf);
        setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnOkBjfActionPerformed

    private void jFmtQuantiBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtQuantiBjfActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtQuantiBjfActionPerformed

    private void jFmtQuantiBjfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFmtQuantiBjfKeyReleased
        if (!jFmtQuantiBjf.getText().isEmpty()) {
            double unitario = Util.strDouble(jFmtValorUniBjf.getText());
            int quantidade = Util.strInt(jFmtQuantiBjf.getText());
            jFmtTotalBjf.setText(String.valueOf(quantidade * unitario));
        } else {
            jFmtTotalBjf.setText("0");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtQuantiBjfKeyReleased

    private void jCboProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboProdutoItemStateChanged
        if (jCboProduto.getSelectedIndex() != -1) {
            jFmtQuantiBjf.setText("1");
            ProdutoBjf produtoBjf = (ProdutoBjf) jCboProduto.getSelectedItem();
            jFmtValorUniBjf.setText(Util.doubleStr(produtoBjf.getPrecoBjf()));
            
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jCboProdutoItemStateChanged

    private void jFmtValorUniBjfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFmtValorUniBjfKeyReleased
        if (jFmtValorUniBjf.getText().isEmpty() == false) {
            double unitario = Util.strDouble(jFmtValorUniBjf.getText());
            int quantidade = Util.strInt(jFmtQuantiBjf.getText());
            jFmtTotalBjf.setText(String.valueOf(quantidade * unitario));
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtValorUniBjfKeyReleased

    private void jFmtQuantiBjfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFmtQuantiBjfFocusLost
        // TODO add your handling code here:
        if (!jFmtQuantiBjf.getText().isEmpty()) {
            double unitario = Util.strDouble(jFmtValorUniBjf.getText());
            int quantidade = Util.strInt(jFmtQuantiBjf.getText());
            jFmtTotalBjf.setText(String.valueOf(quantidade * unitario));
        } else {
            jFmtTotalBjf.setText("0");
        }
    }//GEN-LAST:event_jFmtQuantiBjfFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendasProduto dialog = new JDlgVendasProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOkBjf;
    private javax.swing.JComboBox<ProdutoBjf> jCboProduto;
    private javax.swing.JFormattedTextField jFmtQuantiBjf;
    private javax.swing.JFormattedTextField jFmtTotalBjf;
    private javax.swing.JFormattedTextField jFmtValorUniBjf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

}
