/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import consultas.JDLgConsultaUsuario;
import consultas.JDlgConsultaClientesBjf;
import consultas.JDlgConsultaFuncionarioBjf;
import consultas.JDlgConsultaProdutoBjf;
import consultas.JDlgConsultasdeVendasBjf;


/**
 *
 * @author duals
 */
public class JFrmPrincipalBjf extends javax.swing.JFrame {
    JDlgUsuariosBjf jDlgUsuariosBjf;
    JDlgClientesBjf jDlgClientesBjf;
    JDlgFuncionariosNovoBjf jDlgFuncionariosNovoBjf;
    JDlgProdutoNovoBjf jDlgProdutoNovoBjf;
    JDlgVendasBjf jDlgVendasBjf;
    JDLgConsultaUsuario jDLgConsultaUsuario;
    JDlgConsultaClientesBjf jDlgConsultaClientesBjf;
    JDlgConsultaFuncionarioBjf jDlgConsultaFuncionarioBjf;
    JDlgConsultaProdutoBjf jDlgConsultaProdutoBjf;
    JDlgConsultasdeVendasBjf jDlgConsultaVendasBjf;

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipalBjf() {
        initComponents();
        setTitle("Sistema de Compra e Venda");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMmuSair = new javax.swing.JMenu();
        jMmuUsuarios = new javax.swing.JMenuItem();
        jMmuClientes = new javax.swing.JMenuItem();
        jMmuFuncionarios = new javax.swing.JMenuItem();
        jMmuFuncionarios1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMmuSairr = new javax.swing.JMenuItem();
        jMmuSair1 = new javax.swing.JMenu();
        jMmuUsuarios1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMmuSair2 = new javax.swing.JMenu();
        jMmuUsuarios2 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMmuUsuarios3 = new javax.swing.JMenuItem();
        jMmuUsuarios4 = new javax.swing.JMenuItem();
        jMmuUsuarios5 = new javax.swing.JMenuItem();
        jMmuUsuarios6 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setBackground(new java.awt.Color(255, 0, 51));

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));
        jPanel1.setForeground(new java.awt.Color(204, 0, 51));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton2.setForeground(new java.awt.Color(255, 0, 153));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grupo.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton2.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setForeground(new java.awt.Color(255, 0, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/client_user.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton3.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setForeground(new java.awt.Color(255, 0, 153));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stats_pie_chart.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton4.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setForeground(new java.awt.Color(255, 0, 153));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/solution.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setMaximumSize(new java.awt.Dimension(60, 45));
        jButton5.setMinimumSize(new java.awt.Dimension(60, 45));
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2970, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1030, Short.MAX_VALUE))
        );

        jButton1.setText("jButton1");

        jMenuBar1.setBackground(new java.awt.Color(255, 0, 102));
        jMenuBar1.setForeground(new java.awt.Color(255, 0, 102));

        jMmuSair.setBackground(new java.awt.Color(255, 0, 102));
        jMmuSair.setForeground(new java.awt.Color(255, 0, 102));
        jMmuSair.setMnemonic('C');
        jMmuSair.setText("Cadastros");
        jMmuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuSairActionPerformed(evt);
            }
        });

        jMmuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMmuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/grupo.png"))); // NOI18N
        jMmuUsuarios.setMnemonic('u');
        jMmuUsuarios.setText("Usuarios");
        jMmuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuariosActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuUsuarios);

        jMmuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMmuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/client_user.png"))); // NOI18N
        jMmuClientes.setMnemonic('c');
        jMmuClientes.setText("Clientes");
        jMmuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuClientesActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuClientes);

        jMmuFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMmuFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/stats_pie_chart.png"))); // NOI18N
        jMmuFuncionarios.setMnemonic('f');
        jMmuFuncionarios.setText("Funcionario");
        jMmuFuncionarios.setMaximumSize(new java.awt.Dimension(32667, 32767));
        jMmuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuFuncionariosActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuFuncionarios);

        jMmuFuncionarios1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMmuFuncionarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/solution2.png"))); // NOI18N
        jMmuFuncionarios1.setMnemonic('f');
        jMmuFuncionarios1.setText("Produtos");
        jMmuFuncionarios1.setMaximumSize(new java.awt.Dimension(32667, 32767));
        jMmuFuncionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuFuncionarios1ActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuFuncionarios1);
        jMmuSair.add(jSeparator1);

        jMmuSairr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMmuSairr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jMmuSairr.setMnemonic('s');
        jMmuSairr.setText("Sair");
        jMmuSairr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuSairrActionPerformed(evt);
            }
        });
        jMmuSair.add(jMmuSairr);

        jMenuBar1.add(jMmuSair);

        jMmuSair1.setForeground(new java.awt.Color(255, 0, 102));
        jMmuSair1.setMnemonic('C');
        jMmuSair1.setText("Movimento");
        jMmuSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuSair1ActionPerformed(evt);
            }
        });

        jMmuUsuarios1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMmuUsuarios1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/focus_group.png"))); // NOI18N
        jMmuUsuarios1.setMnemonic('u');
        jMmuUsuarios1.setText("Vendas");
        jMmuUsuarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuarios1ActionPerformed(evt);
            }
        });
        jMmuSair1.add(jMmuUsuarios1);

        jSeparator2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator2.setDoubleBuffered(true);
        jMmuSair1.add(jSeparator2);

        jMenuBar1.add(jMmuSair1);

        jMmuSair2.setForeground(new java.awt.Color(255, 0, 102));
        jMmuSair2.setMnemonic('C');
        jMmuSair2.setText("Consultas");
        jMmuSair2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuSair2ActionPerformed(evt);
            }
        });

        jMmuUsuarios2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMmuUsuarios2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/positioning.png"))); // NOI18N
        jMmuUsuarios2.setMnemonic('u');
        jMmuUsuarios2.setText("consulta de usuario");
        jMmuUsuarios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuarios2ActionPerformed(evt);
            }
        });
        jMmuSair2.add(jMmuUsuarios2);

        jSeparator3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSeparator3.setDoubleBuffered(true);
        jMmuSair2.add(jSeparator3);

        jMmuUsuarios3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMmuUsuarios3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/positioning.png"))); // NOI18N
        jMmuUsuarios3.setMnemonic('u');
        jMmuUsuarios3.setText("consulta de funcionario");
        jMmuUsuarios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuarios3ActionPerformed(evt);
            }
        });
        jMmuSair2.add(jMmuUsuarios3);

        jMmuUsuarios4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMmuUsuarios4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/positioning.png"))); // NOI18N
        jMmuUsuarios4.setMnemonic('u');
        jMmuUsuarios4.setText("consulta de Cliente");
        jMmuUsuarios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuarios4ActionPerformed(evt);
            }
        });
        jMmuSair2.add(jMmuUsuarios4);

        jMmuUsuarios5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMmuUsuarios5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/positioning.png"))); // NOI18N
        jMmuUsuarios5.setMnemonic('u');
        jMmuUsuarios5.setText("consulta de produto");
        jMmuUsuarios5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuarios5ActionPerformed(evt);
            }
        });
        jMmuSair2.add(jMmuUsuarios5);

        jMmuUsuarios6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMmuUsuarios6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/positioning.png"))); // NOI18N
        jMmuUsuarios6.setMnemonic('u');
        jMmuUsuarios6.setText("consulta de vendas");
        jMmuUsuarios6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMmuUsuarios6ActionPerformed(evt);
            }
        });
        jMmuSair2.add(jMmuUsuarios6);

        jMenuBar1.add(jMmuSair2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMmuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuariosActionPerformed
        // TODO add your handling code here
        JDlgUsuariosBjf jDlgUsuarios = new JDlgUsuariosBjf(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMmuUsuariosActionPerformed

    private void jMmuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuClientesActionPerformed
        // TODO add your handling code here:
        JDlgClientesBjf jDlgClientes = new JDlgClientesBjf(this, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMmuClientesActionPerformed

    private void jMmuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuFuncionariosActionPerformed
        JDlgFuncionariosNovoBjf jDlgFuncionariosNovo = new JDlgFuncionariosNovoBjf(this, true);
        jDlgFuncionariosNovo.setVisible(true);
    }//GEN-LAST:event_jMmuFuncionariosActionPerformed

    private void jMmuFuncionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuFuncionarios1ActionPerformed
        // TODO add your handling code here:
        JDlgProdutoNovoBjf jDlgProdutoNovo = new JDlgProdutoNovoBjf(this, true);
        jDlgProdutoNovo.setVisible(true);
    }//GEN-LAST:event_jMmuFuncionarios1ActionPerformed

    private void jMmuSairrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuSairrActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMmuSairrActionPerformed

    private void jMmuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuSairActionPerformed

    private void jMmuUsuarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuarios1ActionPerformed
         JDlgVendasBjf jDlgVendasBjf = new JDlgVendasBjf(this, true);
        jDlgVendasBjf.setVisible(true);            // TODO add your handling code here:
    }//GEN-LAST:event_jMmuUsuarios1ActionPerformed

    private void jMmuSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuSair1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuSair1ActionPerformed

    private void jMmuUsuarios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuarios2ActionPerformed
        // TODO add your handling code here:
    jDLgConsultaUsuario = new JDLgConsultaUsuario(null, true);
    jDLgConsultaUsuario.setTitle("Consultas Usuarios"); 
    jDLgConsultaUsuario.setVisible(true);
    }//GEN-LAST:event_jMmuUsuarios2ActionPerformed

    private void jMmuSair2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuSair2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuSair2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      JDlgUsuariosBjf jDlgUsuarios = new JDlgUsuariosBjf(this, true);
        jDlgUsuarios.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         JDlgClientesBjf jDlgClientes = new JDlgClientesBjf(this, true);
        jDlgClientes.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
JDlgFuncionariosNovoBjf jDlgFuncionariosNovo = new JDlgFuncionariosNovoBjf(this, true);
        jDlgFuncionariosNovo.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
JDlgProdutoNovoBjf jDlgProdutoNovo = new JDlgProdutoNovoBjf(this, true);
        jDlgProdutoNovo.setVisible(true);       
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMmuUsuarios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuarios3ActionPerformed
    jDlgConsultaFuncionarioBjf = new JDlgConsultaFuncionarioBjf(null, true);
    jDlgConsultaFuncionarioBjf.setTitle("Consultas Funcionario"); 
    jDlgConsultaFuncionarioBjf.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jMmuUsuarios3ActionPerformed

    private void jMmuUsuarios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuarios4ActionPerformed
    jDlgConsultaClientesBjf = new JDlgConsultaClientesBjf(null, true);
    jDlgConsultaClientesBjf.setTitle("Consultas Clientes"); 
    jDlgConsultaClientesBjf.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuUsuarios4ActionPerformed

    private void jMmuUsuarios5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuarios5ActionPerformed
    jDlgConsultaProdutoBjf = new JDlgConsultaProdutoBjf(null, true);
    jDlgConsultaProdutoBjf.setTitle("Consultas Produtos"); 
    jDlgConsultaProdutoBjf.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuUsuarios5ActionPerformed

    private void jMmuUsuarios6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMmuUsuarios6ActionPerformed
    jDlgConsultaVendasBjf = new JDlgConsultasdeVendasBjf(null, true);
    jDlgConsultaVendasBjf.setTitle("Consultas Vendas"); 
    jDlgConsultaVendasBjf.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMmuUsuarios6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipalBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipalBjf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMmuClientes;
    private javax.swing.JMenuItem jMmuFuncionarios;
    private javax.swing.JMenuItem jMmuFuncionarios1;
    private javax.swing.JMenu jMmuSair;
    private javax.swing.JMenu jMmuSair1;
    private javax.swing.JMenu jMmuSair2;
    private javax.swing.JMenuItem jMmuSairr;
    private javax.swing.JMenuItem jMmuUsuarios;
    private javax.swing.JMenuItem jMmuUsuarios1;
    private javax.swing.JMenuItem jMmuUsuarios2;
    private javax.swing.JMenuItem jMmuUsuarios3;
    private javax.swing.JMenuItem jMmuUsuarios4;
    private javax.swing.JMenuItem jMmuUsuarios5;
    private javax.swing.JMenuItem jMmuUsuarios6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
