/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import view.*;
import CONTROLEBJF.UsuariosControleBjf;
import bean.UsuariosBjf;
import dao.UsuariosDAOBjf;
import static java.util.Collections.list;
import java.util.List;

/**
 *
 * @author duals
 */




public class JDLgConsultaUsuario extends javax.swing.JDialog {
private UsuariosControleBjf usuariosControleBjf;
UsuariosBjf usuariosBjf;    
UsuariosDAOBjf usuariosDAOBjf;
 UsuariosControleBjf usuariocontrol = new UsuariosControleBjf();
/**
     * Creates new form JDLgConsultaUsuario
     */
    public JDLgConsultaUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        usuariosControleBjf = new UsuariosControleBjf();
        usuariosDAOBjf = new UsuariosDAOBjf();
        List lista = usuariosDAOBjf.listAll();
        usuariosControleBjf.setList(lista);
        jTable1.setModel(usuariosControleBjf);
        setTitle("Controle de Usuário");
        setLocationRelativeTo(null);
    }
    
//    public UsuariosBjf viewBean() {
//        usuariosBjf.setNomeBjf(jTxtNomeBjf.getText());
//        usuariosBjf.setCpfBjf(jFmtCpfBjf.getText());
//        return usuariosBjf;
//    }
//
//    public UsuariosBjf beanView(UsuariosBjf usuarioBjf) {
//        jTxtNomeBjf.setText(usuariosBjf.getNomeBjf());
//         jFmtCpfBjf.setText(usuariosBjf.getCpfBjf());
//        return usuariosBjf;
//  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtNomeBjf = new javax.swing.JTextField();
        jBtnConcluirBjf = new javax.swing.JButton();
        jFmtCpfBjf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nome:");

        jTxtNomeBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeBjfActionPerformed(evt);
            }
        });

        jBtnConcluirBjf.setText("Consultar");
        jBtnConcluirBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConcluirBjfActionPerformed(evt);
            }
        });

        jFmtCpfBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpfBjfActionPerformed(evt);
            }
        });

        jLabel3.setText("CPF:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFmtCpfBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnConcluirBjf)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnConcluirBjf)
                    .addComponent(jFmtCpfBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Consultas de Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeBjfActionPerformed

    private void jBtnConcluirBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConcluirBjfActionPerformed
//
//          usuariosBjf = viewBean();
////          usuariosDAOBjf.insert(usuariosBjf);
//          usuariosControleBjf = new UsuariosControleBjf();
//          List lista = usuariosDAOBjf.listNome(jTxtNomeBjf.getText());
//          usuariosControleBjf.setList(lista);
//         jTable1.setModel(usuariosControleBjf);
  
// 
// List lista = usuariosDAOBjf.listNome(jTxtNomeBjf.getText());
// usuariocontrol.setList(lista);
 if (jTxtNomeBjf.getText().equals("") && jFmtCpfBjf.getText().equals("")){
            List lista = usuariosDAOBjf.listNome(jTxtNomeBjf.getText());
            usuariosControleBjf.setList(lista);
        } else {
            if (! jTxtNomeBjf.getText().equals("") && ! jFmtCpfBjf.getText().equals("")){
                List lista = usuariosDAOBjf.listNomeCpf(jTxtNomeBjf.getText(), jFmtCpfBjf.getText());
                usuariosControleBjf.setList(lista);
            } else {
                if (! jTxtNomeBjf.getText().equals("")){
                    List lista = usuariosDAOBjf.listNome(jTxtNomeBjf.getText());
                    usuariosControleBjf.setList(lista);
                }
                if(! jFmtCpfBjf.getText().equals("")){
                    List lista = usuariosDAOBjf.listCpf(jFmtCpfBjf.getText());
                    usuariosControleBjf.setList(lista); 
                }
            } 
        }
        
                                                   

//setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnConcluirBjfActionPerformed

    private void jFmtCpfBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpfBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpfBjfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDLgConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDLgConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDLgConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDLgConsultaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDLgConsultaUsuario dialog = new JDLgConsultaUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConcluirBjf;
    private javax.swing.JFormattedTextField jFmtCpfBjf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtNomeBjf;
    // End of variables declaration//GEN-END:variables
}
