




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import CONTROLEBJF.FuncionarioControleBjf;
import bean.FuncionarioBjf;
import dao.FuncionarioDAO;
import java.util.Collections;
import static java.util.Collections.list;
import java.util.List;
import tools.Util;

/**
 *
 * @author duals
 */
public class JDlgConsultaFuncionarioBjf extends javax.swing.JDialog {
    FuncionarioBjf funcionarioBjf;    
    FuncionarioDAO funcionarioDAO;
    FuncionarioControleBjf funcionarioControleBjf = new FuncionarioControleBjf();
    
    /**
     * Creates new form JDlgConsultaFuncionarioBjf
     */
    public JDlgConsultaFuncionarioBjf(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        funcionarioControleBjf = new FuncionarioControleBjf();
        funcionarioDAO = new FuncionarioDAO();
        List lista = funcionarioDAO.listAll();
        funcionarioControleBjf.setList(lista);
        jTable1.setModel(funcionarioControleBjf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtNomeBjf = new javax.swing.JTextField();
        jBtnConcluirBjf = new javax.swing.JButton();
        jFmtSalarioBjf = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Consultas de Funcionarios");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Nome:");

        jTxtNomeBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeBjfActionPerformed(evt);
            }
        });

        jBtnConcluirBjf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConcluirBjf.setText("Consultar");
        jBtnConcluirBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConcluirBjfActionPerformed(evt);
            }
        });

        jFmtSalarioBjf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtSalarioBjfActionPerformed(evt);
            }
        });

        jLabel3.setText("Salario:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText(" FUNCIONARIOS NÃO TEM ACESSO Á SALÁRIOS DE ESTAGIARIOS!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jFmtSalarioBjf, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addComponent(jBtnConcluirBjf)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(153, 153, 153))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNomeBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnConcluirBjf)
                    .addComponent(jFmtSalarioBjf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(217, 217, 217))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNomeBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeBjfActionPerformed

    private void jBtnConcluirBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConcluirBjfActionPerformed
//        if (jTxtNomeBjf.getText().isEmpty() && jFmtSalarioBjf.getText().isEmpty()) {
//            List lista = funcionarioDAO.listNome(jTxtNomeBjf.getText());
//            funcionarioControleBjf.setList(lista);
//        } else {
//            if (!jTxtNomeBjf.getText().isEmpty() && !jFmtSalarioBjf.getText().isEmpty()) {
//                double salario = Double.parseDouble(jFmtSalarioBjf.getText());  
//                List lista = funcionarioDAO.listNomeSalario(jTxtNomeBjf.getText(), salario);
//                funcionarioControleBjf.setList(lista);
//            } else {
//                if (!jTxtNomeBjf.getText().isEmpty()) {
//                    List lista = funcionarioDAO.listNome(jTxtNomeBjf.getText());
//                    funcionarioControleBjf.setList(lista);
//                }
//                if (!jFmtSalarioBjf.getText().isEmpty()) {
//                    double salario = Double.parseDouble(jFmtSalarioBjf.getText());  
//                    List lista = funcionarioDAO.listSalario(salario);
//                    funcionarioControleBjf.setList(lista);
//                    }
//                }
//            }
//if (jTxtNomeBjf.getText().isEmpty() && jFmtSalarioBjf.getText().isEmpty()) {
//    // Caso em que ambos estão vazios - buscar todos
//    List lista = funcionarioDAO.listarTodos();
//    funcionarioControleBjf.setList(lista);
//} else {
//    if (!jTxtNomeBjf.getText().isEmpty() && !jFmtSalarioBjf.getText().isEmpty()) {
//        // Caso em que ambos, nome e salário, são fornecidos
//        double salario = Double.parseDouble(jFmtSalarioBjf.getText());
//        List lista = funcionarioDAO.listNomeSalario(jTxtNomeBjf.getText(), salario);
//        funcionarioControleBjf.setList(lista);
//    } else {
//        if (!jTxtNomeBjf.getText().isEmpty()) {
//            // Caso em que apenas o nome é fornecido
//            List lista = funcionarioDAO.listNome(jTxtNomeBjf.getText());
//            funcionarioControleBjf.setList(lista);
//        }
//
//        if (!jFmtSalarioBjf.getText().isEmpty()) {
//            // Caso em que apenas o salário é fornecido
//            double salario = Double.parseDouble(jFmtSalarioBjf.getText());
//
//            // Verifica se o salário é acima de R$ 100
//            if (salario > 100.0) {
//                List lista = funcionarioDAO.listSalario(salario);
//                funcionarioControleBjf.setList(lista);
//            } else {
//                // Adicione uma lógica aqui para lidar com salários abaixo de R$ 100 se necessário
//                // por padrão, poderia mostrar uma mensagem ou realizar outra ação
//            }
//        }
//    }
//}
if (jTxtNomeBjf.getText().isEmpty() && jFmtSalarioBjf.getText().isEmpty()) {
    List lista = funcionarioDAO.listarTodos();
    funcionarioControleBjf.setList(lista);
} else {
    if (!jTxtNomeBjf.getText().isEmpty() && !jFmtSalarioBjf.getText().isEmpty()) {
        double salario = Double.parseDouble(jFmtSalarioBjf.getText());
        List lista = funcionarioDAO.listNomeSalario(jTxtNomeBjf.getText(), salario);
        funcionarioControleBjf.setList(lista);
    } else {
        if (!jTxtNomeBjf.getText().isEmpty()) {
            List lista = funcionarioDAO.listNome(jTxtNomeBjf.getText());
            funcionarioControleBjf.setList(lista);
        }

        if (!jFmtSalarioBjf.getText().isEmpty()) {
            double salario = Double.parseDouble(jFmtSalarioBjf.getText());

            if (salario > 100) {
                List lista = funcionarioDAO.listSalario(salario);
                funcionarioControleBjf.setList(lista);
            } else {
                // Adicione uma lógica aqui para lidar com salários abaixo de R$ 100 se necessário
                // por padrão, poderia mostrar uma mensagem ou realizar outra ação
                // ou então, você pode optar por não definir a lista se o salário for abaixo de R$ 100
                Util.mensagem("Você só poder realizar consultas de salário acima de R$100,00!Obrigada.");
                funcionarioControleBjf.setList(Collections.emptyList()); 
               } 
    
        
                        
    
          
        }
    }
}

    }//GEN-LAST:event_jBtnConcluirBjfActionPerformed

    private void jFmtSalarioBjfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtSalarioBjfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtSalarioBjfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaFuncionarioBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaFuncionarioBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaFuncionarioBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgConsultaFuncionarioBjf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgConsultaFuncionarioBjf dialog = new JDlgConsultaFuncionarioBjf(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnConcluirBjf;
    private javax.swing.JFormattedTextField jFmtSalarioBjf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtNomeBjf;
    // End of variables declaration//GEN-END:variables
}
