package bean;
// Generated 16/12/2023 15:44:11 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClienteBjf generated by hbm2java
 */
@Entity
@Table(name = "cliente_bjf",
        catalog = "db_bianca_ferraz"
)
public class ClienteBjf implements java.io.Serializable {

    private int idclienteBjf;
    private String nomeBjf;
    private String emailBjf;
    private String telefoneBjf;
    private String estadoCivilBjf;
    private String profissaoBjf;
    private String rgBjf;
    private String cpfBjf;
    private Date dataNascBjf;
    private String enderecoBjf;
    private String estadoBjf;
    private String cidadeBjf;
    private String cepBjf;
    private Date dataRegistroBjf;
    private String paisBjf;

    public ClienteBjf() {
    }

    /**
     *
     * @param idclienteBjf
     * @param nomeBjf
     * @param emailBjf
     * @param telefoneBjf
     * @param estadoCivilBjf
     * @param profissaoBjf
     * @param rgBjf
     * @param cpfBjf
     * @param dataNascBjf
     * @param enderecoBjf
     * @param estadoBjf
     * @param cidadeBjf
     * @param cepBjf
     * @param dataRegistroBjf
     * @param paisBjf
     */
    public ClienteBjf(int idclienteBjf, String nomeBjf, String emailBjf, String telefoneBjf, String estadoCivilBjf, String profissaoBjf, String rgBjf, String cpfBjf, Date dataNascBjf, String enderecoBjf, String estadoBjf, String cidadeBjf, String cepBjf, Date dataRegistroBjf, String paisBjf) {
        this.idclienteBjf = idclienteBjf;
        this.nomeBjf = nomeBjf;
        this.emailBjf = emailBjf;
        this.telefoneBjf = telefoneBjf;
        this.estadoCivilBjf = estadoCivilBjf;
        this.profissaoBjf = profissaoBjf;
        this.rgBjf = rgBjf;
        this.cpfBjf = cpfBjf;
        this.dataNascBjf = dataNascBjf;
        this.enderecoBjf = enderecoBjf;
        this.estadoBjf = estadoBjf;
        this.cidadeBjf = cidadeBjf;
        this.cepBjf = cepBjf;
        this.dataRegistroBjf = dataRegistroBjf;
        this.paisBjf = paisBjf;
    }

    @Id

    @Column(name = "idcliente_bjf", unique = true, nullable = false)
    public int getIdclienteBjf() {
        return this.idclienteBjf;
    }

    public void setIdclienteBjf(int idclienteBjf) {
        this.idclienteBjf = idclienteBjf;
    }

    @Column(name = "nome_bjf", nullable = false, length = 50)
    public String getNomeBjf() {
        return this.nomeBjf;
    }

    public void setNomeBjf(String nomeBjf) {
        this.nomeBjf = nomeBjf;
    }

    @Column(name = "email_bjf", nullable = false, length = 50)
    public String getEmailBjf() {
        return this.emailBjf;
    }

    public void setEmailBjf(String emailBjf) {
        this.emailBjf = emailBjf;
    }

    @Column(name = "telefone_bjf", nullable = false, length = 14)
    public String getTelefoneBjf() {
        return this.telefoneBjf;
    }

    public void setTelefoneBjf(String telefoneBjf) {
        this.telefoneBjf = telefoneBjf;
    }

    @Column(name = "estadoCivil_bjf", nullable = false, length = 50)
    public String getEstadoCivilBjf() {
        return this.estadoCivilBjf;
    }

    public void setEstadoCivilBjf(String estadoCivilBjf) {
        this.estadoCivilBjf = estadoCivilBjf;
    }

    @Column(name = "profissao_bjf", nullable = false, length = 50)
    public String getProfissaoBjf() {
        return this.profissaoBjf;
    }

    public void setProfissaoBjf(String profissaoBjf) {
        this.profissaoBjf = profissaoBjf;
    }

    @Column(name = "rg_bjf", nullable = false, length = 20)
    public String getRgBjf() {
        return this.rgBjf;
    }

    public void setRgBjf(String rgBjf) {
        this.rgBjf = rgBjf;
    }

    @Column(name = "cpf_bjf", nullable = false, length = 20)
    public String getCpfBjf() {
        return this.cpfBjf;
    }

    public void setCpfBjf(String cpfBjf) {
        this.cpfBjf = cpfBjf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dataNasc_bjf", nullable = false, length = 10)
    public Date getDataNascBjf() {
        return this.dataNascBjf;
    }

    public void setDataNascBjf(Date dataNascBjf) {
        this.dataNascBjf = dataNascBjf;
    }

    @Column(name = "endereco_bjf", nullable = false, length = 50)
    public String getEnderecoBjf() {
        return this.enderecoBjf;
    }

    public void setEnderecoBjf(String enderecoBjf) {
        this.enderecoBjf = enderecoBjf;
    }

    @Column(name = "estado_bjf", nullable = false, length = 50)
    public String getEstadoBjf() {
        return this.estadoBjf;
    }

    public void setEstadoBjf(String estadoBjf) {
        this.estadoBjf = estadoBjf;
    }

    @Column(name = "cidade_bjf", nullable = false, length = 50)
    public String getCidadeBjf() {
        return this.cidadeBjf;
    }

    public void setCidadeBjf(String cidadeBjf) {
        this.cidadeBjf = cidadeBjf;
    }

    @Column(name = "cep_bjf", nullable = false, length = 50)
    public String getCepBjf() {
        return this.cepBjf;
    }

    public void setCepBjf(String cepBjf) {
        this.cepBjf = cepBjf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dataRegistro_bjf", nullable = false, length = 10)
    public Date getDataRegistroBjf() {
        return this.dataRegistroBjf;
    }

    public void setDataRegistroBjf(Date dataRegistroBjf) {
        this.dataRegistroBjf = dataRegistroBjf;
    }

    @Column(name = "pais_bjf", nullable = false, length = 50)
    public String getPaisBjf() {
        return this.paisBjf;
    }

    public void setPaisBjf(String paisBjf) {
        this.paisBjf = paisBjf;
    }

    public String toString() {
        return nomeBjf;

    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof ClienteBjf) {

            ClienteBjf ClienteBjf = (ClienteBjf) object;
            if (this.getIdclienteBjf() == ClienteBjf.getIdclienteBjf()) {
                return true;
            }
        }
        return false;

    }
}
