package bean;
// Generated 16/12/2023 15:44:11 by Hibernate Tools 4.3.1

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FuncionarioBjf generated by hbm2java
 */
@Entity
@Table(name = "funcionario_bjf",
        catalog = "db_bianca_ferraz"
)
public class FuncionarioBjf implements java.io.Serializable {

    private int idfuncionarioBjf;
    private String nomeBjf;
    private String emailBjf;
    private String numeroTelefoneBjf;
    private String cpfBjf;
    private String sexoBjf;
    private String departamentoBjf;
    private double salarioBjf;

    public FuncionarioBjf() {
    }

    public FuncionarioBjf(int idfuncionarioBjf, String nomeBjf, String emailBjf, String numeroTelefoneBjf, String cpfBjf, String sexoBjf, String departamentoBjf, double salarioBjf) {
        this.idfuncionarioBjf = idfuncionarioBjf;
        this.nomeBjf = nomeBjf;
        this.emailBjf = emailBjf;
        this.numeroTelefoneBjf = numeroTelefoneBjf;
        this.cpfBjf = cpfBjf;
        this.sexoBjf = sexoBjf;
        this.departamentoBjf = departamentoBjf;
        this.salarioBjf = salarioBjf;
    }

    @Id

    @Column(name = "idfuncionario_bjf", unique = true, nullable = false)
    public int getIdfuncionarioBjf() {
        return this.idfuncionarioBjf;
    }

    public void setIdfuncionarioBjf(int idfuncionarioBjf) {
        this.idfuncionarioBjf = idfuncionarioBjf;
    }

    @Column(name = "nome_bjf", nullable = false, length = 50)
    public String getNomeBjf() {
        return this.nomeBjf;
    }

    public void setNomeBjf(String nomeBjf) {
        this.nomeBjf = nomeBjf;
    }

    @Column(name = "email_bjf", nullable = false, length = 50)
    public String getEmailBjf() {
        return this.emailBjf;
    }

    public void setEmailBjf(String emailBjf) {
        this.emailBjf = emailBjf;
    }

    @Column(name = "numeroTelefone_bjf", nullable = false, length = 14)
    public String getNumeroTelefoneBjf() {
        return this.numeroTelefoneBjf;
    }

    public void setNumeroTelefoneBjf(String numeroTelefoneBjf) {
        this.numeroTelefoneBjf = numeroTelefoneBjf;
    }

    @Column(name = "cpf_bjf", nullable = false, length = 15)
    public String getCpfBjf() {
        return this.cpfBjf;
    }

    public void setCpfBjf(String cpfBjf) {
        this.cpfBjf = cpfBjf;
    }

    @Column(name = "sexo_bjf", nullable = false, length = 20)
    public String getSexoBjf() {
        return this.sexoBjf;
    }

    public void setSexoBjf(String sexoBjf) {
        this.sexoBjf = sexoBjf;
    }

    @Column(name = "departamento_bjf", nullable = false, length = 50)
    public String getDepartamentoBjf() {
        return this.departamentoBjf;
    }

    public void setDepartamentoBjf(String departamentoBjf) {
        this.departamentoBjf = departamentoBjf;
    }

    @Column(name = "salario_bjf", nullable = false, precision = 12)
    public double getSalarioBjf() {
        return this.salarioBjf;
    }

    public void setSalarioBjf(double salarioBjf) {
        this.salarioBjf = salarioBjf;
    }

    public String toString() {
        return nomeBjf;

    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof FuncionarioBjf) {

            FuncionarioBjf FuncionarioBjf = (FuncionarioBjf) object;
            if (this.getIdfuncionarioBjf() == FuncionarioBjf.getIdfuncionarioBjf()) {
                return true;
            }
        }
        return false;

    }

}
