package bean;
// Generated 16/12/2023 15:44:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProdutoVendasBjf generated by hbm2java
 */
@Entity
@Table(name="produto_vendas_bjf"
    ,catalog="db_bianca_ferraz"
)
public class ProdutoVendasBjf  implements java.io.Serializable {


     private Integer idprodutoVendasBjf;
     private ProdutoBjf produtoBjf;
     private VendasBjf vendasBjf;
     private int quantidadeBjf;
     private double valorUnitarioBjf;

    public ProdutoVendasBjf() {
    }

    public ProdutoVendasBjf(ProdutoBjf produtoBjf, VendasBjf vendasBjf, int quantidadeBjf, double valorUnitarioBjf) {
       this.produtoBjf = produtoBjf;
       this.vendasBjf = vendasBjf;
       this.quantidadeBjf = quantidadeBjf;
       this.valorUnitarioBjf = valorUnitarioBjf;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idproduto_vendas_bjf", unique=true, nullable=false)
    public Integer getIdprodutoVendasBjf() {
        return this.idprodutoVendasBjf;
    }
    
    public void setIdprodutoVendasBjf(Integer idprodutoVendasBjf) {
        this.idprodutoVendasBjf = idprodutoVendasBjf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_nome_produto", nullable=false)
    public ProdutoBjf getProdutoBjf() {
        return this.produtoBjf;
    }
    
    public void setProdutoBjf(ProdutoBjf produtoBjf) {
        this.produtoBjf = produtoBjf;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_vendas_Bjf", nullable=false)
    public VendasBjf getVendasBjf() {
        return this.vendasBjf;
    }
    
    public void setVendasBjf(VendasBjf vendasBjf) {
        this.vendasBjf = vendasBjf;
    }

    
    @Column(name="quantidade_bjf", nullable=false)
    public int getQuantidadeBjf() {
        return this.quantidadeBjf;
    }
    
    public void setQuantidadeBjf(int quantidadeBjf) {
        this.quantidadeBjf = quantidadeBjf;
    }

    
    @Column(name="valorUnitario_bjf", nullable=false, precision=10)
    public double getValorUnitarioBjf() {
        return this.valorUnitarioBjf;
    }
    
    public void setValorUnitarioBjf(double valorUnitarioBjf) {
        this.valorUnitarioBjf = valorUnitarioBjf;
    }




}


