package bean;
// Generated 16/12/2023 15:44:11 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutoBjf generated by hbm2java
 */
@Entity
@Table(name = "produto_bjf",
        catalog = "db_bianca_ferraz"
)
public class ProdutoBjf implements java.io.Serializable {

    private int idprodutoBjf;
    private String nomeBjf;
    private String descricaoBjf;
    private String categoriaBjf;
    private double precoBjf;
    private int quantidadeBjf;
    private String fornecedorBjf;
    private String serialBjf;

    public ProdutoBjf() {
    }

    public ProdutoBjf(int idprodutoBjf, String nomeBjf, String descricaoBjf, String categoriaBjf, double precoBjf, int quantidadeBjf, String fornecedorBjf, String serialBjf) {
        this.idprodutoBjf = idprodutoBjf;
        this.nomeBjf = nomeBjf;
        this.descricaoBjf = descricaoBjf;
        this.categoriaBjf = categoriaBjf;
        this.precoBjf = precoBjf;
        this.quantidadeBjf = quantidadeBjf;
        this.fornecedorBjf = fornecedorBjf;
        this.serialBjf = serialBjf;
    }

    @Id

    @Column(name = "idproduto_bjf", unique = true, nullable = false)
    public int getIdprodutoBjf() {
        return this.idprodutoBjf;
    }

    public void setIdprodutoBjf(int idprodutoBjf) {
        this.idprodutoBjf = idprodutoBjf;
    }

    @Column(name = "nome_bjf", nullable = false, length = 60)
    public String getNomeBjf() {
        return this.nomeBjf;
    }

    public void setNomeBjf(String nomeBjf) {
        this.nomeBjf = nomeBjf;
    }

    @Column(name = "descricao_bjf", nullable = false)
    public String getDescricaoBjf() {
        return this.descricaoBjf;
    }

    public void setDescricaoBjf(String descricaoBjf) {
        this.descricaoBjf = descricaoBjf;
    }

    @Column(name = "categoria_bjf", nullable = false, length = 20)
    public String getCategoriaBjf() {
        return this.categoriaBjf;
    }

    public void setCategoriaBjf(String categoriaBjf) {
        this.categoriaBjf = categoriaBjf;
    }

    @Column(name = "preco_bjf", nullable = false, precision = 12)
    public double getPrecoBjf() {
        return this.precoBjf;
    }

    public void setPrecoBjf(double precoBjf) {
        this.precoBjf = precoBjf;
    }

    @Column(name = "quantidade_bjf", nullable = false)
    public int getQuantidadeBjf() {
        return this.quantidadeBjf;
    }

    public void setQuantidadeBjf(int quantidadeBjf) {
        this.quantidadeBjf = quantidadeBjf;
    }

    @Column(name = "fornecedor_bjf", nullable = false)
    public String getFornecedorBjf() {
        return this.fornecedorBjf;
    }

    public void setFornecedorBjf(String fornecedorBjf) {
        this.fornecedorBjf = fornecedorBjf;
    }

    @Column(name = "serial_bjf", nullable = false, length = 45)
    public String getSerialBjf() {
        return this.serialBjf;
    }

    public void setSerialBjf(String serialBjf) {
        this.serialBjf = serialBjf;
    }

    public String toString() {
        return nomeBjf;

    }
}
