package bean;
// Generated 16/12/2023 15:44:11 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasBjf generated by hbm2java
 */
@Entity
@Table(name = "vendas_bjf",
         catalog = "db_bianca_ferraz"
)
public class VendasBjf implements java.io.Serializable {

    private int idvendasBjf;
    private ClienteBjf clienteBjf;
    private FuncionarioBjf funcionarioBjf;
    private Date datadaVendasBjf;
    private double valorTotalBjf;

    public VendasBjf() {
    }

    public VendasBjf(int idvendasBjf, ClienteBjf clienteBjf, FuncionarioBjf funcionarioBjf, Date datadaVendasBjf, double valorTotalBjf) {
        this.idvendasBjf = idvendasBjf;
        this.clienteBjf = clienteBjf;
        this.funcionarioBjf = funcionarioBjf;
        this.datadaVendasBjf = datadaVendasBjf;
        this.valorTotalBjf = valorTotalBjf;
    }

    @Id

    @Column(name = "idvendas_bjf", unique = true, nullable = false)
    public int getIdvendasBjf() {
        return this.idvendasBjf;
    }

    public void setIdvendasBjf(int idvendasBjf) {
        this.idvendasBjf = idvendasBjf;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_cliente_bjf", nullable = false)
    public ClienteBjf getClienteBjf() {
        return this.clienteBjf;
    }

    public void setClienteBjf(ClienteBjf clienteBjf) {
        this.clienteBjf = clienteBjf;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fk_funcionario_bjf", nullable = false)
    public FuncionarioBjf getFuncionarioBjf() {
        return this.funcionarioBjf;
    }

    public void setFuncionarioBjf(FuncionarioBjf funcionarioBjf) {
        this.funcionarioBjf = funcionarioBjf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "datadaVendas_bjf", nullable = false, length = 10)
    public Date getDatadaVendasBjf() {
        return this.datadaVendasBjf;
    }

    public void setDatadaVendasBjf(Date datadaVendasBjf) {
        this.datadaVendasBjf = datadaVendasBjf;
    }

    @Column(name = "valorTotal_bjf", nullable = false, precision = 10)
    public double getValorTotalBjf() {
        return this.valorTotalBjf;
    }

    public void setValorTotalBjf(double valorTotalBjf) {
        this.valorTotalBjf = valorTotalBjf;
    }

}
